#! /usr/bin/perl

use warnings;
use strict;

my $seq = "";
my $sample = "";
my @LaLines;
my %seqs;
my @samples;

open F, $ARGV[0] or die"Can't open Fasta";
while (<F>) {
	chomp($_);
	push @LaLines, $_;
}
close F;

my $i = 0;
while ($i<$#LaLines+1) {
	if ($LaLines[$i] =~ />/) {
		if ($sample ne "") {
			$seqs{$sample} = $seq;			
		}
		chomp($LaLines[$i]);
		$sample = substr($LaLines[$i], 1);
		push @samples, $sample;
		$seq = "";
	} else {
		$seq = $seq.$LaLines[$i];
	}
	$i=$i+1;
#	print $i."\t".$sample."\n";
}
$seqs{$sample} = $seq;
my $num_samps = $#samples+1;


print $num_samps."\t".length($seqs{$samples[1]})."\n";
foreach my $sample_name (@samples) {
my $spaces = 10-length($sample_name);
	print substr($sample_name,0,10)." "x$spaces.$seqs{$sample_name}."\n";
#	print $sample_name."\n";
}




